application_id = 'io.github.qwersyk.Newelle'

scalable_dir = join_paths('hicolor', 'scalable', 'apps')
install_data(
  join_paths(scalable_dir, ('@0@.svg').format(application_id)),
  install_dir: join_paths(get_option('datadir'), 'icons', scalable_dir)
)

symbolic_dir = join_paths('hicolor', 'symbolic', 'apps')
install_data(
  join_paths(symbolic_dir, ('@0@-symbolic.svg').format(application_id)),
  install_dir: join_paths(get_option('datadir'), 'icons', symbolic_dir)
)

symbolic_dir = join_paths(get_option('datadir'), 'icons/hicolor/symbolic/apps')
install_data (
    'internet-symbolic.svg',
    'view-show-symbolic.svg',
    'plus-symbolic.svg',
    'attach-symbolic.svg',
    'circle-crossed-symbolic.svg',
    'check-plain-symbolic.svg',
    'user-trash-symbolic.svg',
    'info-outline-symbolic.svg',
    'document-edit-symbolic.svg',
    'zoom-in-symbolic.svg',
    'zoom-out-symbolic.svg',
    'brain-augemnted-symbolic.svg',
    'question-round-outline-symbolic.svg',
    'controls-big-symbolic.svg',
    'vcard-symbolic.svg',
    'settings-symbolic.svg',
    'sidebar-show-right-symbolic.svg',
    'go-home-symbolic.svg',
    'detach-symbolic.svg',
    'sidebar-show-left-symbolic.svg',
    'magic-wand-symbolic.svg',
    'lobehub-ai2-symbolic.svg',
    'lobehub-aya-symbolic.svg',
    'lobehub-baichuan-symbolic.svg',
    'lobehub-bytedance-symbolic.svg',
    'lobehub-chatglm-symbolic.svg',
    'lobehub-claude-symbolic.svg',
    'lobehub-commanda-symbolic.svg',
    'lobehub-deepcogito-symbolic.svg',
    'lobehub-deepseek-symbolic.svg',
    'lobehub-flux-symbolic.svg',
    'lobehub-gemma-symbolic.svg',
    'lobehub-hunyuan-symbolic.svg',
    'lobehub-ibm-symbolic.svg',
    'lobehub-internlm-symbolic.svg',
    'lobehub-lg-symbolic.svg',
    'lobehub-liquid-symbolic.svg',
    'lobehub-meta-symbolic.svg',
    'lobehub-microsoft-symbolic.svg',
    'lobehub-minimax-symbolic.svg',
    'lobehub-mistral-symbolic.svg',
    'lobehub-moonshot-symbolic.svg',
    'lobehub-nvidia-symbolic.svg',
    'lobehub-openai-symbolic.svg',
    'lobehub-openchat-symbolic.svg',
    'lobehub-poolside-symbolic.svg',
    'lobehub-qwen-symbolic.svg',
    'lobehub-snowflake-symbolic.svg',
    'lobehub-stability-symbolic.svg',
    'lobehub-tii-symbolic.svg',
    'lobehub-yi-symbolic.svg',
    'lobehub-wenxin-symbolic.svg',
    'lobehub-zai-symbolic.svg',
    'emblem-default-symbolic.svg',
    'tools-symbolic.svg',
    'user-bookmarks-symbolic.svg',
    'chat-bubbles-text-symbolic.svg',
    'branch-symbolic.svg',
    'call-emergency-symbolic.svg',
    'skills-symbolic.svg',
    'key-symbolic.svg',
    'audio-input-microphone-symbolic.svg',
    'extension-symbolic.svg',
    'list-drag-handle-symbolic.svg',
    'folder-visiting-symbolic.svg',
    'edit-undo-symbolic.svg',
    install_dir: symbolic_dir
)
install_data (
    'warning-outline-symbolic.svg',
    install_dir: symbolic_dir
)
install_data (
    'star-filled-rounded-symbolic.svg',
    install_dir: symbolic_dir
)
install_data (
    'update-symbolic.svg',
    install_dir: symbolic_dir
)
install_data (
    'search-folder-symbolic.svg',
    install_dir: symbolic_dir
)
install_data (
  'right-large-symbolic.svg',
  install_dir: symbolic_dir
)
install_data (
  'left-large-symbolic.svg',
  install_dir: symbolic_dir
)
install_data (
  'gnome-terminal-symbolic.svg',
  install_dir: symbolic_dir
)
install_data(
  'lobehub-icons.LICENSE',
  install_dir: join_paths(get_option('datadir'), 'licenses', 'newelle')
)
